#!/bin/env -S ansible-playbook -i inventory
---
- name: manage panos host
  connection: ansible.builtin.local
  hosts: all
  gather_facts: false

  vars:

    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  pre_tasks:

    - name: panos_facts
      paloaltonetworks.panos.panos_facts:
        provider: "{{ provider }}"
        gather_subset:
          - system
          - interfaces

  tasks:

     - name: Imported tasks
       block:
         - ansible.builtin.include_tasks: panos_device.yaml
         - ansible.builtin.include_tasks: panos_network.yaml
         - ansible.builtin.include_tasks: panos_objects.yaml
         - ansible.builtin.include_tasks: panos_policies.yaml

  handlers:

    - name: panos_commit
      paloaltonetworks.panos.panos_commit_firewall:
        provider: '{{ provider }}'
