#!/bin/env -S ansible-playbook -i inventory
---
- name: manage panos host
  hosts: all
  gather_facts: false

  vars:

    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  pre_tasks:

    - name: Fail if not panos
      ansible.builtin.fail:
      no_log: true
      when: ansible_network_os != "paloaltonetworks.panos"

    - name: Gather all legacy facts
      paloaltonetworks.panos.panos_facts:
        provider: "{{ provider }}"
        gather_subset:
          - system

  tasks:

    - ansible.builtin.debug:
        msg: "{{ ansible_facts }}"
#    - meta: end_play

    - name: vwire interfaces
      paloaltonetworks.panos.panos_interface:
        provider: "{{ provider }}"
        if_name: "{{ item }}"
        comment: "Ansible Managed"
        mode: "virtual-wire"
      ignore_errors: true
      loop:
        - ethernet1/3
        - ethernet1/4

    - name: Create Vwire
      paloaltonetworks.panos.panos_virtual_wire:
        provider: '{{ provider }}'
        name: 'vwire1'
        interface1: 'ethernet1/3'
        interface2: 'ethernet1/4'
        pass_through: true
        state: present
